### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by hajosattila** [fape/service.subtitles.supersubtitles#9]
Szia!
Várható még frissítés a közeljövőben, mert CoreELEC Omega 21.1.1 alatt nem működik...

**Comment by fape** [comment]
Helló, Én kb napi szinten használom desktopon windows-sal és rpi4-n osmc-vel. Általában frissen tartom, sztem mind a kettő 21.x-es lehet. Nem tapasztaltam hibát. 
Tudnál küldeni [logokat](https://forum.kodi.tv/showthread.php?tid=288153) vagy kezdetnek egy fájl név is elég lehet, aminél hibát tapasztalsz? Behúzd a médiatárba vagy csak fájlként lejátszod le?

**Comment by hajosattila** [comment]
Egy reboot megoldotta :) elnezest a lamasagert, de viszonylag ritkan inditom ujra a boxot :)
Remek plugin, koszi!
